Dropping unused extra control socket
We were establishing two sockets to the control port: one via stem that we
used, and other via the socket modle that did nothing except to
connect/disconnect.

Also adding some error handling to our Controller.from_port() call. Actually,
the error handling for the old socket was broken. It had a line with simply
"raise", which would've resulted in a TypeError...

>>> raise
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType